### ISSUE TITLE
Intermittent 502 bad gateway error

### ISSUE THREAD

**Issue by sandrodz** [jwilder/nginx-proxy#1383]
I've seen other bad gateway errors, but they are mostly failing all the time.

My issue is different, I get 502 intermittently.
And mostly on 1 website. But some other websites are also getting it.

I am not sure were to start diagnosing this particular problem, since it's so random.

**Comment by maxkratz** [comment]
I can confirm this issue. I'm using jwilder/nginx-proxy together with a lets-encrypt-container and I get various 502s over nearly all containers. Sometimes it is working properly but some containers may fail more often than others.

**Comment by banagale** [comment]
@cglusky Hey there—yes. For this project I am Postgres in the same stack. 

After posting my findings I got some feedback from @mjhea0 that my network port mapping may have contributed to situation. 

I made those changes after I had taken care of it, and I didn’t go back to validate it to be the cause. 

See [his comments here](https://github.com/testdrivenio/django-on-docker/issues/28). 

I would not be surprised if improperly configured networking was the part of the problem, because that combined with the stack would make it relatively uncommon. 

And that would explain why the issue hasn’t been addressed and that there aren’t very many examples from other people. 

Regardless please do post what you find out just in case someone like yourself runs into the same issue.

**Comment by maxkratz** [comment]
> @sandrodz or @maxkratz Are either of you also running a postgres container in your stack?

No postgres container on my side. Meanwhile I (hopefully) resolved all my 502 errors with this nginx-stack. The error was ... hard to find (at least in my opinion): I've cloned various containers with portainer. The clones had the **same** MAC address as the original containers -> This lead to the fact that my nginx container was unable to connect to the upstreams from time to time due to doubled layer 2 adresses.

I changed from portainer as a "management" tool to docker-compose and had no 502 errors afterwards.

**Comment by cglusky** [comment]
Thanks for feedback.  I fixed mine by moving to a managed Postgres instance on DigitalOcean for staging/demo instance.  We shall just deal with intermittent 502's on our test stack.  Spent days trying to tweak Gunicorn and Nginx configs as well as trying different DigitalOcean droplet sizes to make sure we were not victims of OOM etc.  I would like to suggest that nginx-proxy add env vars so we can set max_fails etc in Upstream block but not clear they have an impact if not running as a load balancer.

**Comment by banagale** [comment]
@cglusky I found the changes I made that resolved the issue. 

You can observe them in my [public fork of nginx-proxy](https://github.com/PerchLive/nginx-proxy/commits/master). See line 18 of [this commit](https://github.com/PerchLive/nginx-proxy/commit/0af9107346d87cbbdb28b654f7a61d1e7461347e#diff-a2a77c71854a4489d896f49c59a5f864e5b1e290f6b1ba16f9f39c1a32829c57R18), which shows the conditional behavior needed to do the configuration in the Upstream block. 

In this case I set a fail\_timeout that exceeds 3000 years. So it would still be intermittent, just very infrequent. :)

If you're using docker, you may be able to substitute in my build of nginx-proxy and see if the problem fixes. Again, if you have any luck please post.

I agree it would have been nice to have a config var, though I believe the maintainer prefers to do as minimal changes as possible for stability reasons.

**Comment by cglusky** [comment]
Thanks @banagale.  Yes, having a config var that would allow us to exclude a container from Upstream may fix this issue.  We think it may be the postgres container being automatically added to Upstream that causes it to be subjected to passive health checks from Nginx that in turn make Gunicorn unhappy and result in the 502's.  I have no proof other than some empirical evidence plus your findings.

**Comment by mabdullahabid** [comment]
Any updates on this? I removed ports: 5432:5432 from my compose file postgres section but it still gets added to the upstream. I'm using postgres:13-alpine image. I don't recall this happening in 12-alpine as I have used the same setup in multiple projects. Any ideas as to what might have changed? Is it the newer release of nginx-proxy or postgres?
