### ISSUE TITLE
VIRTUAL_PORT not  forwarded

### ISSUE THREAD

**Issue by amuchembled** [jwilder/nginx-proxy#214]
Hi,

I use this awesome container since severals months.
But today i've got a problem when deploying another container. 

This is coming from the VIRTUAL_PORT that seems not recognized when accessing to my hostname. (I have to type : http://my.domain.com:8080 instead of http://my.domain.com)
For information I've set : -e VIRTUAL_HOST=my.domain.com -e VIRTUAL_PORT=8080

Also, upstream information in nginx configuration doesn't contain PORT information :/

Thank you for your help :)

EDIT : In complement, all my previous containers doesn't work now :/, nginx don't want to route to the defined container's ports

EDIT 2: Ok, the problem was from a new gitlab container which breaks nginx oO

RESOLVED

**Comment by amuchembled** [comment]
I think this was resolved but new containers doesn't want to be routed to the specified port...

**Comment by xloup** [comment]
Hello, I seem to have the same problem.

Nginx listens on 80:80 and 443:443

When runing mysql image container I am adding 
-e VIRTUAL_HOST=mysql.myhost.com \
-e VIRTUAL_PORT=3306 \

but I still cannot acces the mysql server. The objectif is that nginx proxies the service on port 80 of the host to 3306 of the mysql container for the host mysql.myhost.com.

**Comment by amuchembled** [comment]
"nginx-proxy" has been updated, and it's now easier to use.

I think that you just have to deploy your container with :
-e VIRTUAL_HOST=mysql.myhost.com \
-p 80:3306

the port forwarding should be done automatically

**Comment by xloup** [comment]
thanks for your reply,
I cannot use the -p 80:3306 line because port 80 is already used by nginx_proxy. I tried that and get the message : Bind for 0.0.0.0:80 failed: port is already allocated 

This seems normal to me, it is nginx proxy that listens already to 80, I juste need to tell nginx_proxy to forward 80 to 3306 for this host ... but This does not seem to work currently...

I made sure I had the latest image nginx_proxy ...

**Comment by amuchembled** [comment]
OK my fault... that seems normal...
Have you tried to don't specified any port ?

For mysql just run : 
docker run --name some-mysql -e VIRTUAL_HOST=mysql.myhost.com -d mysql

nginx-proxy should find the 3306 port automatically and do the DNS redirection on this port.

**Comment by md5** [comment]
The `nginx-proxy` image can't proxy the MySQL protocol, so this isn't going to work.

**Comment by xloup** [comment]
I just tried that also, the doc seems to indicate what you suggest is true, but that does not work neither.

Nothing exists on that host on that port, and typing docker ps does not indicate that 80 is forwarded to 3306 as it does for other "normal" containers like 80:80 ...

**Comment by md5** [comment]
Last time this came up, I looked into [MySQL Proxy](https://dev.mysql.com/downloads/mysql-proxy/) a bit. It may be possible to get MySQL Proxy to route to different backends, but it would involve some Lua scripting. As far as I know, nobody has made a Docker image that does this, but it *might* be possible using the underlying `docker-gen` command that this image uses to generate either a Lua script or a config file that could be read by a Lua script to achieve this.

**Comment by md5** [comment]
Note, it would not be name-based proxying, since the MySQL protocol doesn't include the equivalent of an HTTP `Host` header. It would have to be something based on the database name. I'm also not sure if this could even work, since MySQL supports the `USE` command which can switch databases for an already established connection.

**Comment by xloup** [comment]
ah ok thanks for your answer - will check your suggestions
