### ISSUE TITLE
Proxying to a second nginx container 

### ISSUE THREAD

**Issue by bleen** [jwilder/nginx-proxy#664]
I generally have 3 or 4 separate local dev envs for Drupal development and now that I'm moving from a native local environment to docker (based on [docker4drupal](https://github.com/wodby/docker4drupal)) I'm trying to use nginx-proxy proxy URLs like dev.d7 an dev.d8 but I can't anything to work.

I have a docker-composer.json just for nginx-proxy in the root of my ~/Sites directory: 
```
version: "2"

services:
  # Create a revers proxy to sit in front of local dev sites
  nginx-proxy:
    image: jwilder/nginx-proxy
    #net: d8_default
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
```

Then in my ~/Sites/d8 folder I have a separate docker-composer.json based on the [docker-composer.json included in docker4drupal](https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml):
```
version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb:1.0.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  php:
    image: wodby/drupal-php:7.0-1.0.0
#    image: wodby/drupal-php:5.6-1.0.0
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:8000
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/drupal-nginx:1.0.0
    environment:
      VIRTUAL_HOST: dev.d8
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
#      NGINX_DOCROOT: web # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
    volumes_from:
      - php
 #   expose:
 #     - 8000
 #   ports:
 #     - "8000:80"
 #   networks:
 #     - nginx-proxy

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"
```

I've tried all sorts of permutations of specifying ports, adding networks, exposing ports but I'm not able to browse http://dev.d8 ...  Any help is hugely appreciated.

**Comment by DblK** [comment]
Aside this project you need to set up a DNS Server (most likely Bind9) to redirect domain to your IP.
I use "pstauffer/bind:stable" with success.

My steps are:
1) Add domain to the dns server
2) Launch container with VIRTUAL_HOST parameter
3) Enjoy ;)

**Comment by bleen** [comment]
Shouldn't it be enough to add:
```
0.0.0.0    dev.d8 
```
to my /etc/hosts?

**Comment by DblK** [comment]
Should be enough.
Regarding to your issue, uncomment your port section in your nginx container of the second docker-compose.
Try to launch only this file and navigate to localhost:8000 and see if you can see the website.
If it's working, then go to dev.d8:8000.
If it's working, then start the other docker-compose file.

If it's not working try to add networks in both docker-compose file to match and allow the two nginx to see each other. If the previous steps didn't work, you will need to dig into it and it is not related to nginx-proxy.

**Comment by bleen** [comment]
> Try to launch only this file and navigate to localhost:8000 and see if you can see the website.
This works

> If it's working, then go to dev.d8:8000.
This does not work. I'll start digging into the docker4drupal setup and see if I can figure out why

If it's working, then start the other docker-compose file.
> to be continued ...

Thanks for your help.

**Comment by DblK** [comment]
I have another idea, replace in your host 0.0.0.0 by your current IP.
Maybe this should solve the problem.

If not you can still install an DNS Server than will forward to the IP with the docker nginx-proxy.

**Comment by bleen** [comment]
> Try to launch only this file and navigate to localhost:8000 and see if you can see the website.

This (still) works

> If it's working, then go to dev.d8:8000.

This now works. (I had a mismatch in my ```PHP_SITE_NAME``` and ```NGINX_SERVER_NAME```)

> If it's working, then start the other docker-compose file.

When I start the nginx-proxy docker-compose then browsing to dev.d8:8000 but browsing to dev.d8 (the goal) does not work. 

>I have another idea, replace in your host 0.0.0.0 by your current IP

I assume you mean for me to change 0.0.0.0 to 127.0.0.1 ... if so, this did not help. 

>If not you can still install an DNS Server than will forward to the IP with the docker nginx-proxy.

If I have to go down this path, then wouldnt I just point that DNS server to my docker4drupal nginx. In other words, the nginx-proxy would become irrelevant, no?

**Comment by DblK** [comment]
Okay if  _dev.d8:8000_ works now, just add VIRTUAL_PORT=8000 to your compose file and it should do the trick.

**Comment by bleen** [comment]
Bad news is that Adding ```VIRTUAL_PORT: 8000``` to my docker4drupal docker-compose.yml doesn't help regardless of whether I use 0.0.0.0 or 127.0.0.1 in my ```/etc/hosts``` file.

Good news is that it doesnt work in a slightly different way: Now I get an ERR_EMPTY_RESPONSE instead of ERR_NAME_NOT_RESOLVED that I had been receiving previously. I still get a perfectly valid 200 at http://dev.d8:8000

**Comment by DblK** [comment]
Can you post your last version of your docker compose?
I will try to find some time to test it.

Thanks

Le 3 janv. 2017 5:42 PM, "Alexander Ross" <notifications@github.com> a
écrit :

**Comment by bleen** [comment]
Note: I changed from ```dev.d8``` to ```d8.local``` at some point...

Here is the docker-compose.yml located in ```~/Sites```

```
version: "2"

services:

  # Create a reverse proxy to sit in front of local dev sites
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
```

Here is the docker-compose.yml located in ```~/Sites/d8```:

```
version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb:1.0.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    image: wodby/drupal-php:7.0-1.0.0
#    image: wodby/drupal-php:5.6-1.0.0
    environment:
      PHP_SITE_NAME: d8.local
      PHP_HOST_NAME: localhost:8000
      PHP_DOCROOT: www/docroot # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      # PHP_XDEBUG_ENABLED: 1
      # PHP_XDEBUG_AUTOSTART: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - ./:/var/www/html
      - ~/.drush/:/home/www-data/.drush #Share drush settings from the host machine
#      - d4d-unison-sync:/var/www/html:rw # Replace volume to this to use docker-sync for macOS users

  nginx:
    image: wodby/drupal-nginx:1.0.0
    environment:
      VIRTUAL_HOST: d8.local
      VIRTUAL_PORT: 8000
      NGINX_SERVER_NAME: d8.local
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: www/docroot # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
    volumes_from:
      - php
    ports:
      - "8000:80"

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"
```

Here is my ```etc/hosts```:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost

#127.0.0.1         d8.local
0.0.0.0         d8.local
```

**Comment by Toilal** [comment]
I had same kind of issues with drupal, fixed with those settings

```
proxy_buffer_size          1024k;
proxy_buffers              16 512k;
proxy_busy_buffers_size    2048k;
```

Seems to be related to #694

**Comment by huuchi207** [comment]
Have the same issue. Here is my docker-compose.yml:
`version: "3.7"
services:
  site-db:
    image: mysql:5.7
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - site-net
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
    restart: always
    ports: 
      - 3306:3306
  web1:
    depends_on:
       - site-db
    image: wordpress
    networks:
      - site-net
    restart: always
    environment:
      WORDPRESS_DB_NAME: web1
      WORDPRESS_DB_HOST: site-db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PWD}
      VIRTUAL_HOST: my-app.local
      VIRTUAL_PORT: 3000
    working_dir: /var/www/html
    volumes:
      - D:\Project\Web\mypham2:/var/www/html
    ports:
      - "3000:80"
    expose:
      - 3000
  web2:
    depends_on:
       - site-db
    image: wordpress:5.0
    networks:
      - site-net
    restart: always
    environment:
      WORDPRESS_DB_NAME: web2
      WORDPRESS_DB_HOST: site-db:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PWD}
    working_dir: /var/www/html
    volumes:
      - ./sites/web2:/var/www/html
    ports:
      - "8000:80"
  phpmyadmin:
    depends_on:
      - site-db
    networks:
      - site-net
    links:
      - site-db
    image: phpmyadmin/phpmyadmin
    container_name: 'site-phpmyadmin'
    environment:
      PMA_HOST: site-db
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PWD}
      MYSQL_USERNAME: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PWD}
      MYSQL_PASSWORD: ${DB_PWD}
    ports:
      - '8081:80'
    volumes: 
      - /sessions
networks:
  site-net:
    driver: bridge
  default:
    external:
      name: nginx-proxy`

and: 
`version: "3.1"
services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
networks:
  default:
    external:
      name: nginx-proxy`
